# Site settings
title: ESDN Collections
email: jmignault@metro.org
description: > # this means to ignore newlines until "baseurl:"
  Councils and collections from the Empire State Digital Network.
baseurl: "/collstool" # the subpath of your site, e.g. /blog/
url: "http://ESDNHub.github.io" # the base hostname & protocol for your site
twitter_username: NYSDigital
github_username:  ESDNHub

# Build settings
markdown: kramdown
gems: [octopress-debugger]
